export const enum ErrorCode {
    ENVIRONMENT_ERROR = 'E_001',
    BAD_PARAMETERS = 'E_002',
    RESOURCE_NOT_FOUND = 'E_003',
    PAYMENT_W_NOT_AUTHORIZED = 'E_004',
    PAYMENT_TOKEN_ERROR = 'E_005',
    INTERNAL_ERROR = 'E_006',
    CURRENT_RIDE = 'E_007',
    NO_PAYMENT_METHOD = 'E_008'
}